### ISSUE TITLE
rolling response or delay to answer (first byte empty)

### ISSUE THREAD

**Issue by Grominet** [pyhys/minimalmodbus#18]
Hello,

Sorry, I am not an Modbus or python expert, but I don't know how continue to solve my issue :
I've an modbus equipment (Nilan combi 300), and use an FDTI USB plugin RPI to communicate.

My issue is I can't get a stable response, and that give checksum error. I've two script to explained issue :
- one the response is stable 
- second the response is "rolling", and I success to get one right response after 5-6times. 

I never have issue with transmitting a request, the equipment react always at first sending, but response is always... uncertain. 
I have also try another USB-serial chip, same issue.
Note the first byte from stable response is always an empty byte, so I've put some resistor for biasing but without more success, and with two type of cable

## First script output (stable, always the same):
```
sudo python nilan2.py
TESTING Nilan Connection
__main__.Nilan<id=0x76c99238, address=30, mode=rtu, close_port_after_each_call=False, precalculate_read_size=False, debug=True, serial=Serial<id=0x76ab0530, open=True>(port='/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_00000000-if00-port0', baudrate=19200, bytesize=8, parity='E', stopbits=1, timeout=1.1, xonxoff=False, rtscts=False, dsrdtr=False)>

MinimalModbus debug mode. Writing to instrument (expecting 1000 bytes back): '\x1e\x03\x03\xeb\x00\x01\xf6\x15' (1E 03 03 EB 00 01 F6 15)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1502978904014.4 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x00\x1e\x03\x02\x00\x02\xacG\x00' (00 1E 03 02 00 02 AC 47 00) (9 bytes), roundtrip time: 1101.7 ms. Timeout setting: 1100.0 ms.

Traceback (most recent call last):
  File "nilan2.py", line 68, in <module>
    old_userVent_value = n.get_userVent()
  File "nilan2.py", line 45, in get_userVent
    return self.read_register(1003, numberOfDecimals=0, signed=False, functioncode=3)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 258, in read_register
    return self._genericCommand(functioncode, registeraddress, numberOfDecimals=numberOfDecimals, signed=signed)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 697, in _genericCommand
    payloadFromSlave = self._performCommand(functioncode, payloadToSlave)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 798, in _performCommand
    payloadFromSlave = _extractPayload(response, self.address, self.mode, functioncode)
  File "/usr/local/lib/python2.7/dist-packages/minimalmodbus.py", line 1075, in _extractPayload
    raise ValueError(text)
ValueError: Checksum error in rtu mode: 'G\x00' instead of '\\\x1b' . The response is: '\x00\x1e\x03\x02\x00\x02\xacG\x00' (plain response: '\x00\x1e\x03\x02\x00\x02\xacG\x00')
```

First script .py : 
```
#!/usr/bin/env python

#reference https://minimalmodbus.readthedocs.io/en/master/apiminimalmodbus.html#minimalmodbus.Instrument.read_register
import minimalmodbus
import serial

__author__  = "Nick Ma"

class Nilan( minimalmodbus.Instrument ):
    """Instrument class for nilan heat pump.
    communication via RS485
    """

    HOLDINGREG_OFFSET = 10000

    def __init__(self, portname, slaveaddress=30):
        minimalmodbus.Instrument.__init__(self, portname, slaveaddress)

        self.serial.baudrate = 19200
        self.serial.stopbits = 1
        self.serial.bytesize = 8

        self.serial.parity = serial.PARITY_EVEN
        self.serial.timeout = 1.1  #timeout to 1000ms because I discovered roundtrip times as high as 898.5 ms

        self.serial.rtscts = False

        self.mode = minimalmodbus.MODE_RTU
        self.precalculate_read_size = False
        self.FIRST_BYTE_READING = 1
        self.handle_local_echo = False

    def is_manual_loop1(self):
        """Return True if loop1 is in manual mode."""
        return self.read_register(273, 1) > 0


    def get_t11Top(self):
        """Return the setpoint (SP) target for loop1."""
        return self.read_register(211, numberOfDecimals=2,
            signed=True, functioncode=4)

    def get_userVent(self):
        """This is a holding register -> functioncode=3"""
        return self.read_register(1003, numberOfDecimals=0, signed=False, functioncode=3)

    def set_userVent(self, speed=2):
        if (speed<0) or (speed>4):
            return
        return self.write_register(1003, speed)

########################
## Testing the module ##
########################

if __name__ == '__main__':
#    NILAN_SERIAL_PORT = '/dev/ttyUSB0'
    NILAN_SERIAL_PORT = '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_00000000-if00-port0'

    print( 'TESTING Nilan Connection')

    n = Nilan(NILAN_SERIAL_PORT)
    n.debug = True
    print(n)

    ## starting demo
    old_userVent_value = n.get_userVent()
    print( 'old userVentSet:             {0}'.format( old_userVent_value ))

    n.debug = False
    new_designated_userVent = 1 if old_userVent_value==2 else 2
    n.set_userVent(new_designated_userVent)
    print( 'new userVentSet:             {0}'.format( n.get_userVent()       ))

    print( 'Connection to the Nilan instrument looks good!' )

pass
```

## Second script output (with a loop) with multiple response :
```
16:23:59 08/17/17 CEST

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xd2\x00\x01\x93\x9c' (1E 04 00 D2 00 01 93 9C)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1502979839213.4 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x00\x1e\x04\x02\x0ba\xea' (00 1E 04 02 0B 61 EA) (7 bytes), roundtrip time: 41.7 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xd2\x00\x01\x93\x9c' (1E 04 00 D2 00 01 93 9C)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1003.7 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '*\x00\x00\x1e\x04\x02\x0b' (2A 00 00 1E 04 02 0B) (7 bytes), roundtrip time: 15.6 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xd2\x00\x01\x93\x9c' (1E 04 00 D2 00 01 93 9C)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1006.4 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: 'a\xea*\x00\x00\x1e\x04' (61 EA 2A 00 00 1E 04) (7 bytes), roundtrip time: 16.2 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xd2\x00\x01\x93\x9c' (1E 04 00 D2 00 01 93 9C)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1005.0 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x02\x0ba\xea*\x00\x00' (02 0B 61 EA 2A 00 00) (7 bytes), roundtrip time: 7.0 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xd2\x00\x01\x93\x9c' (1E 04 00 D2 00 01 93 9C)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1004.9 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x1e\x04\x02\x0ba\xea*' (1E 04 02 0B 61 EA 2A) (7 bytes), roundtrip time: 0.4 ms. Timeout setting: 1100.0 ms.

lecture OK
Temp. maison =  29.13

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xcf\x00\x01\x03\x9a' (1E 04 00 CF 00 01 03 9A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 3.9 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x00\x00' (00 00) (2 bytes), roundtrip time: 1101.5 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xcf\x00\x01\x03\x9a' (1E 04 00 CF 00 01 03 9A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1004.0 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x00\x1e\x04\x02\x05\n\xaf' (00 1E 04 02 05 0A AF) (7 bytes), roundtrip time: 15.8 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xcf\x00\x01\x03\x9a' (1E 04 00 CF 00 01 03 9A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1004.9 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\xa5\x00\x00\x1e\x04\x02\x05' (A5 00 00 1E 04 02 05) (7 bytes), roundtrip time: 22.8 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xcf\x00\x01\x03\x9a' (1E 04 00 CF 00 01 03 9A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1006.4 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\n\xaf\xa5\x00\x00\x1e\x04' (0A AF A5 00 00 1E 04) (7 bytes), roundtrip time: 16.6 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xcf\x00\x01\x03\x9a' (1E 04 00 CF 00 01 03 9A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1005.4 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x02\x05\n\xaf\xa5\x00\x00' (02 05 0A AF A5 00 00) (7 bytes), roundtrip time: 16.4 ms. Timeout setting: 1100.0 ms.

exception lecture

MinimalModbus debug mode. Writing to instrument (expecting 7 bytes back): '\x1e\x04\x00\xcf\x00\x01\x03\x9a' (1E 04 00 CF 00 01 03 9A)
MinimalModbus debug mode. No sleep required before write. Time since previous read: 1004.6 ms, minimum silent period: 2.01 ms.
MinimalModbus debug mode. Response from instrument: '\x1e\x04\x02\x05\t\xef\xa4' (1E 04 02 05 09 EF A4) (7 bytes), roundtrip time: 0.4 ms. Timeout setting: 1100.0 ms.

lecture OK
Temp. air pulsee =  12.89
```

Second script with multiple answer :
```
#!/usr/bin/env python
import minimalmodbus
import requests
import time
import sys
import datetime
import random
import traceback

#sys.stdout = open('/home/pi/nilan.log', 'w')
#instrument = minimalmodbus.Instrument('/dev/ttyUSB0', 30) # port name, slave address (in decimal)
#instrument.serial.parity   = minimalmodbus.serial.PARITY_EVEN

#sudo strace -ewrite -p 2222   pour voir le stdout quand il tourne en bg

hum_hist0 = 0
hum_hist1 = 0
flag_hum = 0


def lire_nilan (un, deux, trois, quatre):
    success = 0
    while (success != 1):
        try:
            resultat = instrument.read_register(un, deux, trois, quatre)
            print 'lecture OK'
#            print traceback.format_exc()
            success = 1
        except:
            print 'exception lecture'
#            print traceback.format_exc()
            time.sleep (1)
    return resultat

def ecrire_nilan (un, deux, trois):
    success = 0
    while (success != 1):
            try:
                instrument.write_register(un, deux, trois)
                print 'write OK'
                success = 1
            except:
                print 'exception ecriture'
#                print traceback.format_exc()
                time.sleep (1)
while (1):
    try:

        #instrument = minimalmodbus.Instrument('/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9O3R1L9-if00-port0', 30) # port name, slave address (in decimal)
        instrument = minimalmodbus.Instrument('/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_00000000-if00-port0', 30) # port name, slave address (in decimal)
        #instrument = minimalmodbus.Instrument('/dev/ttyUSB0', 30)
        instrument.serial.timeout  = 1.1   # seconds
        instrument.serial.parity   = minimalmodbus.serial.PARITY_EVEN
        instrument.CLOSE_PORT_AFTER_EACH_CALL = True
        instrument.debug = True
        print time.strftime('%X %x %Z')



        ## Read temperature (PV = ProcessValue) ##
        temp_maison = lire_nilan(210, 2, 4, True) # Registernumber, number of decimals
        print 'Temp. maison = ', temp_maison
        if temp_maison < 5 :
            os.exit()

        temp_puls = lire_nilan(207, 2, 4, True) # Registernumber, number of decimals
        print 'Temp. air pulsee = ', temp_puls

        ventil_consigne = lire_nilan(1003, 0, 3, True)
        print 'Ventilation 1003 = ', ventil_consigne

#        ecrire_nilan(1003,2,0)

    except:
        print 'Exception'
        print traceback.format_exc()
        sys.exit(0)
```

**Comment by pyhys** [comment]
I am not sure what the problem with the instrument is here. Minimalmodbus sends (1E 04 00 D2 00 01 93 9C), and the instrument should answer with something that starts with 1E 04. Unknown what causes this.
