### ISSUE TITLE
Modbus RTU minimalmodbus.InvalidResponseError

### ISSUE THREAD

**Issue by Bogaerts-Gaetan** [pyhys/minimalmodbus#75]
**Explication**
Hello everyone, I am currently in a modbus rtu communication test phase with minimalmodbus to control a Mitsubishi Heavy industries air conditioning unit via an intesis converter. When I modify the 16 bit registers, the change in the air conditioning registers is done fine but this error appears. So I would like to use minimalmodbus and understand this error.
Can you help me?

thank you very much in advance
**code:**
>#!/usr/bin/env python3
import minimalmodbus
import serial
minimalmodbus.BYTEORDER_BIG = 0
minimalmodbus.MODE_RTU = 'rtu'
instrument = minimalmodbus.Instrument('COM3', 1)
instrument.serial.port = 'COM3'
instrument.serial.baudrate = 9600  # Baud
instrument.serial.bytesize = 8
instrument.serial.parity = serial.PARITY_NONE
instrument.serial.stopbits = 2
instrument.serial.timeout = 100
instrument.address = 1
instrument.mode = minimalmodbus.MODE_RTU
instrument.clear_buffers_before_each_transaction = True
instrument.write_register(2, 4)
#temperature = instrument.read_register(2, 1)
instrument.serial.close()

**error :** 
>"C:\Program Files\Python39\python.exe" C:/Users/bogae/Desktop/test_modbus/test_com_clim_modbu/clim.py
Traceback (most recent call last):
  File "C:\Users\bogae\Desktop\test_modbus\test_com_clim_modbu\clim.py", line 19, in <module>
    instrument.write_register(2, 4)
  File "C:\Users\bogae\AppData\Roaming\Python\Python39\site-packages\minimalmodbus.py", line 550, in write_register
    self._generic_command(
  File "C:\Users\bogae\AppData\Roaming\Python\Python39\site-packages\minimalmodbus.py", line 1245, in _generic_command
    payload_from_slave = self._perform_command(functioncode, payload_to_slave)
  File "C:\Users\bogae\AppData\Roaming\Python\Python39\site-packages\minimalmodbus.py", line 1329, in _perform_command
    payload_from_slave = _extract_payload(
  File "C:\Users\bogae\AppData\Roaming\Python\Python39\site-packages\minimalmodbus.py", line 1867, in _extract_payload
    raise InvalidResponseError(text)
minimalmodbus.InvalidResponseError: Checksum error in rtu mode: '\x01\xa0' instead of '8{' . The response is: '\x00\x01\x10\x00\x02\x00\x01\xa0' (plain response: '\x00\x01\x10\x00\x02\x00\x01\xa0')

**Comment by Bogaerts-Gaetan** [comment]
I have tested through another better quality converter and everything works fine. Thank you very much for your time and help
